# Generated by Django 4.0.3 on 2022-03-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_slug_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
